services:
  spring-app:
    image: eclipse-temurin:24-jdk-alpine
    container_name: spring-boot-demo
    working_dir: /app
    volumes:
      - ./target/demo-0.0.1-SNAPSHOT.jar:/app/app.jar:ro
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    restart: always

  postgres:
    image: postgres:17.2-alpine
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: student
    volumes:
      - pgData:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgData:
